name: CI/CD pipe
on:
  push:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  schedule:
    - cron: 0 0 */7 * *  # run once a week

env:
  IMAGE_NAME: rouhim/althttpd
  TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container-image-arch: [ amd64, arm64, arm ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/${{ matrix.container-image-arch }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build container image
        uses: docker/build-push-action@v3
        with:
          file: Containerfile
          tags: ${{ env.IMAGE_NAME }}:${{ env.TAG }}
          platforms: linux/${{ matrix.container-image-arch }}
          outputs: type=oci,dest=image.tar
          push: true

      - name: Update docker hub description
        if: github.ref_name == 'main' # only update description if the branch is main
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: rouhim/althttpd
